/** 50 perguntas — teoria → prática · linguagem de missão didática */
const desafios = [
  {
    tipo: "teoria", nivel: "básico", nivelClass: "intro", topico: "react",
    refs: ["react-geral", "componente", "createRoot"],
    titulo: "O que é React?",
    aprender: `<p><strong>React</strong> monta telas em <strong>componentes</strong> — funções que retornam JSX (HTML + JavaScript).</p>
      <p>No seu <code>contador.html</code>: <code>Contador</code> guarda a lógica, <code>App</code> organiza a página, <code>createRoot</code> liga tudo ao HTML.</p>`,
    explica: `<p>Componente = função com nome maiúsculo que retorna JSX.</p>`,
    porque: "Componentes deixam o código legível — base de qualquer front-end React.",
    quiz: [
      { pergunta: "Um componente React é basicamente:", opcoes: ["uma função que descreve um pedaço da tela (JSX)", "um arquivo CSS", "só HTML sem JavaScript"], correta: 0, explicacao: "Componentes são funções que retornam JSX." },
      { pergunta: "createRoot().render() serve para:", opcoes: ["colocar seu App dentro da div #root do HTML", "criar um botão automaticamente", "importar o Tailwind"], correta: 0, explicacao: "É o ponto de entrada do React na página." },
    ],
    passos: ["Leia o texto acima", "Responda as perguntas", "Verificar"],
  },
  {
    tipo: "pratica", modo: "intro", nivel: "básico", nivelClass: "intro", topico: "react",
    refs: ["useState", "componente"],
    titulo: "Observe um contador funcionando",
    aprender: `<p>Antes de escrever, <strong>observe</strong> como um contador React funciona na prática.</p>`,
    missao: `<p><strong>Missão:</strong> rode o preview, clique em <em>adicionar</em> e entenda o fluxo:</p>
      <p>1) <code>useState</code> guarda o número → 2) <code>{contador}</code> mostra na tela → 3) <code>setContador</code> atualiza no clique.</p>`,
    ferramentas: "<code>useState</code>, <code>onClick</code>, chaves <code>{ }</code> no JSX",
    porque: "React só atualiza o que mudou — por isso o número sobe sem recarregar a página.",
    quiz: [
      { pergunta: "O número que aparece na tela vem de:", opcoes: ["useState (variável contador)", "do CSS", "é fixo no HTML"], correta: 0, explicacao: "contador é a variável do state." },
    ],
    passos: ["Clique <strong>Preview</strong> e veja Contador: 0", "Clique <strong>adicionar</strong> várias vezes", "Responda a pergunta do quiz", "Clique <strong>Verificar</strong>"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador((c) => c + 1)}>adicionar</button>\n    </div>\n  );\n}`,
    dica: "Só observar — no próximo você mesmo monta.",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador((c) => c + 1)}>adicionar</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /useState/.test(c) && /\{contador\}/.test(c), msg: "Mantém useState e {contador}" }, { ok: /setContador/.test(c), msg: "Mantém setContador" }]; },
  },
  {
    tipo: "teoria", nivel: "básico", nivelClass: "intro", topico: "useState",
    refs: ["useState"],
    titulo: "useState — a memória do componente",
    aprender: `<p><code>useState</code> é como a <strong>memória</strong> do seu componente — guarda um valor que pode mudar e, quando muda, a tela atualiza.</p>
      <pre>const [contador, setContador] = React.useState(0)</pre>
      <ul style="margin:8px 0 8px 18px;line-height:1.65">
        <li><code>contador</code> — leia na tela e na lógica</li>
        <li><code>setContador</code> — única forma correta de mudar</li>
        <li><code>0</code> — valor inicial (só na 1ª vez)</li>
      </ul>`,
    porque: "Sem state, a tela seria sempre igual — não teria contador dinâmico.",
    quiz: [
      { pergunta: "useState(0) te devolve:", opcoes: ["um par: [valor, função para atualizar]", "só o número 0", "um botão pronto"], correta: 0, explicacao: "Sempre array com 2 itens." },
      { pergunta: "Para o contador subir de 0 para 1 você deve:", opcoes: ["chamar setContador(...)", "escrever contador = 1 direto", "mudar o CSS"], correta: 0, explicacao: "Nunca atribua direto ao state." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "completar", nivel: "básico", nivelClass: "completar", topico: "useState",
    refs: ["useState", "jsx-chaves"],
    titulo: "Contador que mostra o número na tela",
    aprender: `<p>Você vai montar um contador que <strong>começa em zero</strong> e <strong>exibe o valor</strong> para o usuário.</p>`,
    missao: `<p><strong>Missão:</strong> implemente um contador que guarda o número em memória e mostra <em>Contador: 0</em> na tela.</p>
      <p>No editor, complete as duas partes que faltam (marcadas com <code>___LACUNA___</code>): a declaração do state e a exibição do valor.</p>`,
    ferramentas: "<code>React.useState(0)</code> e <code>{contador}</code> dentro do JSX",
    porque: "Separar memória (useState) de exibição ({contador}) é o coração do React com state.",
    passos: [
      "Na linha do state, troque <code>___LACUNA_1___</code> por <code>React.useState(0)</code>",
      "No &lt;p&gt;, troque <code>___LACUNA_2___</code> por <code>{contador}</code> (com chaves!)",
      "Preview: deve aparecer <strong>Contador: 0</strong>",
      "Verificar",
    ],
    codigo: `function Contador() {\n  const [contador, setContador] = ___LACUNA_1___;\n  return (\n    <div>\n      <p>Contador: ___LACUNA_2___</p>\n    </div>\n  );\n}`,
    dica: "LACUNA_1 = React.useState(0) · LACUNA_2 = {contador}",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: !/___LACUNA/.test(c), msg: "Complete as duas lacunas" }, { ok: /useState\s*\(\s*0\s*\)/.test(c), msg: "useState(0)" }, { ok: /\{contador\}/.test(c), msg: "{contador} no JSX" }]; },
  },
  {
    tipo: "teoria", nivel: "básico", nivelClass: "intro", topico: "jsx",
    refs: ["jsx", "jsx-chaves"],
    titulo: "JSX — mostrar variáveis na tela",
    aprender: `<p>No JSX, <code>{ chaves }</code> = "agora é JavaScript".</p>
      <pre>&lt;p&gt;Olá, {nome}&lt;/p&gt;
&lt;p&gt;Dobro: {contador * 2}&lt;/p&gt;</pre>
      <p>Sem chaves, o React mostra texto literal — a palavra "contador", não o número.</p>`,
    porque: "JSX mistura HTML e lógica — é o que torna React expressivo.",
    quiz: [
      { pergunta: "Para exibir o valor da variável contador:", opcoes: ["{contador}", "contador sem chaves", "&lt;contador&gt;"], correta: 0, explicacao: "Chaves = expressão JavaScript." },
      { pergunta: "No React, class vira:", opcoes: ["className", "class igual HTML", "css"], correta: 0, explicacao: "class é palavra reservada em JS." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "básico", nivelClass: "verde", topico: "jsx",
    refs: ["jsx-chaves"],
    titulo: "Mostrar contador e o dobro",
    aprender: `<p>Valores calculados na hora não precisam de useState extra.</p>`,
    missao: `<p><strong>Missão:</strong> no contador que já tem <code>useState(0)</code>, mostre duas informações:</p>
      <ul style="margin:8px 0 8px 18px"><li>linha com o valor atual</li><li>linha com o dobro desse valor</li></ul>`,
    ferramentas: "<code>{contador}</code> e <code>{contador * 2}</code> em tags &lt;p&gt;",
    passos: ["Adicione &lt;p&gt;Contador: {contador}&lt;/p&gt;", "Adicione &lt;p&gt;Dobro: {contador * 2}&lt;/p&gt;", "Preview e Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      {/* TODO: duas linhas <p> */}\n    </div>\n  );\n}`,
    dica: "Duas tags <p> com {contador} e {contador * 2}",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <p>Dobro: {contador * 2}</p>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /\{contador\}/.test(c), msg: "{contador}" }, { ok: /\*\s*2/.test(c), msg: "contador * 2" }]; },
  },
  {
    tipo: "teoria", nivel: "básico", nivelClass: "intro", topico: "eventos",
    refs: ["onClick", "eventos", "arrow"],
    titulo: "Cliques — onClick no React",
    aprender: `<p>Quando o usuário clica, você passa uma <strong>função</strong> pro botão:</p>
      <pre>&lt;button onClick={() => setContador(contador + 1)}&gt;</pre>
      <p>Erro comum: <code>onClick={setContador(1)}</code> roda na hora do render, não no clique!</p>`,
    porque: "Eventos conectam o que o usuário faz ao state do componente.",
    quiz: [
      { pergunta: "Forma correta de reagir ao clique:", opcoes: ["onClick={() => adicionar()}", "onClick={adicionar()}", "onclick=adicionar"], correta: 0, explicacao: "CamelCase + função, não chamada imediata." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "completar", nivel: "básico", nivelClass: "completar", topico: "eventos",
    refs: ["onClick", "setContador"],
    titulo: "Botão que soma +1 ao clicar",
    missao: `<p><strong>Missão:</strong> faça o botão <em>adicionar</em> somar 1 ao contador cada vez que o usuário clicar.</p>
      <p>O contador já aparece na tela. Falta só fazer o clique funcionar.</p>`,
    ferramentas: "<code>onClick</code> com arrow function <code>() => setContador(...)</code>",
    passos: [
      "Complete o <code>onClick</code> do botão adicionar (onde está ___LACUNA___)",
      "Use: <code>() => setContador(contador + 1)</code>",
      "Preview: clique adicionar e veja o número subir",
      "Verificar",
    ],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={___LACUNA___}>adicionar</button>\n    </div>\n  );\n}`,
    dica: "onClick precisa de função: () => setContador(contador + 1)",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador(contador + 1)}>adicionar</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: !/___LACUNA/.test(c), msg: "Complete o onClick" }, { ok: /setContador/.test(c), msg: "setContador no clique" }]; },
  },
  {
    tipo: "teoria", nivel: "básico", nivelClass: "intro", topico: "setState",
    refs: ["setContador"],
    titulo: "Resetar com valor fixo",
    aprender: `<p>Quando você sabe o valor exato (ex: zero), use <code>setContador(0)</code> direto — sem calcular com o anterior.</p>`,
    quiz: [
      { pergunta: "Para voltar o contador a zero:", opcoes: ["setContador(0)", "contador = 0", "apagar o componente"], correta: 0, explicacao: "set com valor fixo." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "completar", nivel: "básico", nivelClass: "completar", topico: "setState",
    refs: ["setContador"],
    titulo: "Botão resetar para zero",
    missao: `<p><strong>Missão:</strong> adicione um botão <em>resetar</em> que volta o contador para <strong>0</strong> de qualquer valor.</p>
      <p>O botão adicionar já funciona — complete só o resetar.</p>`,
    ferramentas: "<code>setContador(0)</code> no onClick do botão resetar",
    passos: ["Complete o onClick do botão resetar", "Teste: adicionar várias vezes → resetar → volta a 0", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador(contador + 1)}>adicionar</button>\n      <button onClick={___LACUNA___}>resetar</button>\n    </div>\n  );\n}`,
    dica: "() => setContador(0)",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador(contador + 1)}>adicionar</button>\n      <button onClick={() => setContador(0)}>resetar</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /setContador\s*\(\s*0\s*\)/.test(c), msg: "setContador(0) no resetar" }]; },
  },
  {
    tipo: "teoria", nivel: "básico", nivelClass: "intro", topico: "javascript",
    refs: ["math-max"],
    titulo: "Impedir número negativo",
    aprender: `<p><code>Math.max(0, contador - 1)</code> escolhe o maior entre 0 e o resultado — nunca fica negativo.</p>`,
    quiz: [
      { pergunta: "Math.max(0, -3) retorna:", opcoes: ["0", "-3", "3"], correta: 0, explicacao: "Pega o maior dos dois." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "básico", nivelClass: "verde", topico: "javascript",
    refs: ["math-max", "setContador"],
    titulo: "Botão remover (sem ficar negativo)",
    missao: `<p><strong>Missão:</strong> crie um botão <em>remover</em> que diminui 1, mas <strong>nunca deixa o contador abaixo de 0</strong>.</p>
      <p>Adicionar e resetar já existem — você adiciona só o remover.</p>`,
    ferramentas: "<code>Math.max(0, ...)</code> dentro do setContador",
    passos: ["Adicione botão remover", "No clique: setContador com Math.max(0, contador - 1)", "Teste em 0 — não deve ir pra -1", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador(contador + 1)}>adicionar</button>\n      <button onClick={() => setContador(0)}>resetar</button>\n    </div>\n  );\n}`,
    dica: "setContador((p) => Math.max(0, p - 1))",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador(contador + 1)}>adicionar</button>\n      <button onClick={() => setContador(0)}>resetar</button>\n      <button onClick={() => setContador((p) => Math.max(0, p - 1))}>remover</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /remover/i.test(c), msg: 'Botão "remover"' }, { ok: /Math\.max\s*\(\s*0/.test(c), msg: "Math.max(0,...)" }]; },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "prev",
    refs: ["prev"],
    titulo: "Atualização com (prev) =>",
    aprender: `<p>Quando o novo valor depende do anterior, use <code>setContador((prev) => prev + 1)</code> — o React passa o valor mais recente.</p>
      <p>Essencial quando há várias atualizações no mesmo clique.</p>`,
    quiz: [
      { pergunta: "(prev) => prev + 1 é melhor quando:", opcoes: ["o novo valor depende do anterior", "você quer mudar cor", "não usa state"], correta: 0, explicacao: "Forma funcional do setState." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "completar", nivel: "médio", nivelClass: "completar", topico: "prev",
    refs: ["prev"],
    titulo: "Adicionar usando (prev)",
    missao: `<p><strong>Missão:</strong> no botão adicionar, troque a forma de somar para usar <code>(prev) => prev + 1</code> — mais seguro quando o valor anterior importa.</p>`,
    ferramentas: "<code>setContador((prev) => prev + 1)</code>",
    passos: ["Complete ___LACUNA___ no setContador do botão adicionar", "Preview: clique e confira +1", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador(___LACUNA___)}>adicionar</button>\n    </div>\n  );\n}`,
    dica: "(prev) => prev + 1 — prev pode ser (c) ou (atual)",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador((prev) => prev + 1)}>adicionar</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /setContador\s*\(\s*\(?\s*prev/.test(c), msg: "setContador((prev)=>...)" }]; },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "prev",
    titulo: "Somar +2 num único clique",
    aprender: `<p>Duas chamadas <code>setContador((p) => p + 1)</code> no mesmo handler = +2 num clique só.</p>`,
    quiz: [
      { pergunta: "Para +2 num clique você pode:", opcoes: ["chamar setContador com prev duas vezes", "usar contador++ no JSX", "remover useState"], correta: 0, explicacao: "Cada set agenda +1." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "médio", nivelClass: "amarelo", topico: "prev",
    refs: ["prev"],
    titulo: "Botão +2 de uma vez",
    missao: `<p><strong>Missão:</strong> crie um botão <em>+2</em> que aumenta o contador em <strong>2</strong> com um único clique.</p>
      <p>Implemente a função <code>adicionarDois</code> com duas atualizações usando <code>(prev) => prev + 1</code>.</p>`,
    ferramentas: "função <code>adicionarDois</code> + 2x <code>setContador((prev) => prev + 1)</code>",
    passos: ["Complete adicionarDois() no editor", "Botão +2 chama adicionarDois", "Preview: um clique = +2", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  function adicionarDois() {\n    // TODO: somar +2 usando prev duas vezes\n  }\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={adicionarDois}>+2</button>\n    </div>\n  );\n}`,
    dica: "Duas linhas: setContador((prev) => prev + 1);",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  function adicionarDois() {\n    setContador((prev) => prev + 1);\n    setContador((prev) => prev + 1);\n  }\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={adicionarDois}>+2</button>\n    </div>\n  );\n}`,
    validar(c) { const n = (c.match(/setContador\s*\(\s*\(?\s*prev/gi) || []).length; return [{ ok: n >= 2, msg: "2x setContador((prev)=>...)" }]; },
  },
  {
    tipo: "teoria", nivel: "básico", nivelClass: "intro", topico: "arrays",
    refs: ["array-lista", "useState"],
    titulo: "Listas com useState([])",
    aprender: `<p><code>[]</code> = lista. <code>useState([])</code> guarda histórico, tarefas, mensagens...</p>
      <p><code>.length</code> conta quantos itens tem — sem precisar de outro state.</p>`,
    quiz: [
      { pergunta: "useState([]) começa com:", opcoes: ["lista vazia (0 itens)", "número zero", "undefined"], correta: 0, explicacao: "Array vazio." },
      { pergunta: "[10, 20, 30].length vale:", opcoes: ["3", "10", "0"], correta: 0, explicacao: "Quantidade de itens." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "básico", nivelClass: "verde", topico: "arrays",
    refs: ["array-lista"],
    titulo: "Contar itens de uma lista",
    missao: `<p><strong>Missão:</strong> crie um componente que guarda a lista <code>[1, 2, 3]</code> no state e mostra na tela <em>Itens: 3</em>.</p>`,
    ferramentas: "<code>useState([1, 2, 3])</code> e <code>{historico.length}</code>",
    passos: ["Declare historico com useState([1, 2, 3])", "Mostre Itens: {historico.length}", "Verificar"],
    codigo: `function Contador() {\n  return (\n    <div>\n      <p>Itens: </p>\n    </div>\n  );\n}`,
    dica: "const [historico, setHistorico] = React.useState([1, 2, 3]);",
    solucao: `function Contador() {\n  const [historico, setHistorico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      <p>Itens: {historico.length}</p>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /useState\s*\(\s*\[/.test(c), msg: "useState com array" }, { ok: /historico\.length/.test(c), msg: "historico.length" }]; },
  },
  {
    tipo: "teoria", nivel: "básico", nivelClass: "intro", topico: "arrays",
    refs: ["join"],
    titulo: "join() — lista vira texto",
    aprender: `<p><code>historico.join(", ")</code> transforma <code>[1, 2, 3]</code> no texto <em>1, 2, 3</em> numa linha só.</p>
      <p>Útil antes de aprender map — não cria &lt;li&gt;, só string.</p>`,
    quiz: [
      { pergunta: "join serve para:", opcoes: ["mostrar lista como texto numa linha", "apagar itens", "criar botões"], correta: 0, explicacao: "Concatena com separador." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "básico", nivelClass: "verde", topico: "arrays",
    refs: ["join"],
    titulo: "Exibir lista como texto",
    missao: `<p><strong>Missão:</strong> mostre a lista <code>[1, 2, 3]</code> na tela como texto: <em>Lista: 1, 2, 3</em>.</p>`,
    ferramentas: "<code>historico.join(', ')</code> no JSX",
    passos: ["Complete o &lt;p&gt;Lista: ...&lt;/p&gt; com join", "Preview deve mostrar 1, 2, 3", "Verificar"],
    codigo: `function Contador() {\n  const [historico, setHistorico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      <p>Lista: </p>\n    </div>\n  );\n}`,
    dica: "{historico.join(', ')}",
    solucao: `function Contador() {\n  const [historico, setHistorico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      <p>Lista: {historico.join(", ")}</p>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /\.join\s*\(/.test(c), msg: "historico.join(...)" }]; },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "map",
    refs: ["map"],
    titulo: "map() — cada item vira um pedaço de tela",
    aprender: `<p><code>historico.map((n) => &lt;li&gt;{n}&lt;/li&gt;)</code> — percorre a lista e cria um &lt;li&gt; por número.</p>
      <p>Diferente de forEach: map <strong>retorna</strong> algo (no React: elementos JSX).</p>`,
    quiz: [
      { pergunta: "map é usado no React para:", opcoes: ["transformar cada item da lista em JSX", "apagar o array", "somar todos os números"], correta: 0, explicacao: "Retorna novo array de elementos." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "básico", nivelClass: "verde", topico: "map",
    refs: ["map"],
    titulo: "Lista com um &lt;li&gt; por item",
    missao: `<p><strong>Missão:</strong> exiba <code>[1, 2, 3]</code> como uma lista HTML — um &lt;li&gt; para cada número.</p>`,
    ferramentas: "<code>&lt;ul&gt;</code> + <code>historico.map((n) => &lt;li&gt;{n}&lt;/li&gt;)</code>",
    passos: ["Crie &lt;ul&gt; no return", "Dentro: historico.map com &lt;li&gt;{n}&lt;/li&gt;", "Verificar"],
    codigo: `function Contador() {\n  const [historico, setHistorico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      {/* TODO: ul + map */}\n    </div>\n  );\n}`,
    dica: "{historico.map((n) => <li>{n}</li>)} dentro de <ul>",
    solucao: `function Contador() {\n  const [historico, setHistorico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      <ul>{historico.map((n) => <li>{n}</li>)}</ul>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /\.map\s*\(/.test(c), msg: ".map(" }, { ok: /<li/i.test(c), msg: "<li>" }]; },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "map",
    refs: ["map", "array-lista"],
    titulo: "Por que key={i}?",
    aprender: `<p>Em listas, cada &lt;li&gt; precisa de um <code>key</code> — um id pra React saber qual linha é qual.</p>
      <pre>historico.map((n, i) => &lt;li key={i}&gt;{n}&lt;/li&gt;)</pre>`,
    quiz: [
      { pergunta: "key={i} ajuda o React a:", opcoes: ["identificar cada item da lista", "mudar a cor do texto", "somar números"], correta: 0, explicacao: "Evita bugs quando a lista muda." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "básico", nivelClass: "verde", topico: "map",
    refs: ["map"],
    titulo: "Adicionar key em cada linha",
    missao: `<p><strong>Missão:</strong> na lista que você já tem, adicione <code>key={i}</code> em cada &lt;li&gt; — o React exige isso em listas.</p>`,
    ferramentas: "segundo parâmetro do map: <code>(n, i) =></code> e <code>key={i}</code>",
    passos: ["Mude map para (n, i) =>", "Adicione key={i} no &lt;li&gt;", "Verificar"],
    codigo: `function Contador() {\n  const [historico, setHistorico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      <ul>{historico.map((n) => <li>{n}</li>)}</ul>\n    </div>\n  );\n}`,
    dica: "(n, i) => <li key={i}>{n}</li>",
    solucao: `function Contador() {\n  const [historico, setHistorico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      <ul>{historico.map((n, i) => <li key={i}>{n}</li>)}</ul>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /key=\{/.test(c), msg: "key={...}" }, { ok: /\.map\s*\([^)]*,\s*\w+/.test(c), msg: "(n, i) no map" }]; },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "spread",
    refs: ["spread-array"],
    titulo: "Spread [...lista, novo]",
    aprender: `<p>Para adicionar item numa lista no state: <code>[...h, novo]</code> — copia a lista antiga e coloca o novo no final.</p>
      <p>Nunca use <code>push</code> direto — React pode não atualizar a tela.</p>`,
    quiz: [
      { pergunta: "Spread em vez de push porque:", opcoes: ["cria array novo e React detecta mudança", "push é proibido em JS", "spread apaga tudo"], correta: 0, explicacao: "Imutabilidade no state." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "médio", nivelClass: "amarelo", topico: "spread",
    refs: ["spread-array", "prev"],
    titulo: "Salvar cada clique no histórico",
    missao: `<p><strong>Missão:</strong> cada vez que o usuário clica <em>adicionar</em>, guarde o novo valor do contador numa lista <code>historico</code> (começa vazia).</p>
      <p>Dentro do setContador: calcule <code>novo</code>, salve com spread, retorne <code>novo</code>.</p>`,
    ferramentas: "<code>useState([])</code>, <code>setHistorico(h => [...h, novo])</code>, <code>return novo</code>",
    passos: ["Adicione useState([]) para historico", "Em adicionar: const novo, setHistorico com spread, return novo", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  function adicionar() {\n    setContador((prev) => prev + 1);\n  }\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={adicionar}>adicionar</button>\n    </div>\n  );\n}`,
    dica: "setContador((prev) => { const novo = prev+1; setHistorico(h=>[...h,novo]); return novo; })",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  const [historico, setHistorico] = React.useState([]);\n  function adicionar() {\n    setContador((prev) => {\n      const novo = prev + 1;\n      setHistorico((h) => [...h, novo]);\n      return novo;\n    });\n  }\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={adicionar}>adicionar</button>\n    </div>\n  );\n}`,
    validar(c) {
      return [
        { ok: /React\.useState\s*\(\s*\[\s*\]\s*\)/.test(c), msg: "useState([]) para historico" },
        { ok: /setHistorico/.test(c), msg: "setHistorico" },
        { ok: /\[\.\.\.[a-zA-Z_$]+/.test(c), msg: "spread [...h, novo]" },
        { ok: /const\s+novo\s*=/.test(c), msg: "const novo = ..." },
        { ok: /return\s+novo/.test(c), msg: "return novo" },
      ];
    },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "map",
    refs: ["map", "spread-array"],
    titulo: "Lista vazia no começo",
    aprender: `<p>Se <code>historico = []</code>, o map mostra 0 linhas — normal até o usuário clicar adicionar.</p>`,
    quiz: [
      { pergunta: "historico vazio na tela mostra:", opcoes: ["nenhuma linha (lista vazia)", "erro vermelho", "undefined"], correta: 0, explicacao: "map em [] não gera itens." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "médio", nivelClass: "amarelo", topico: "map",
    refs: ["map", "spread-array"],
    titulo: "Mostrar histórico na tela",
    missao: `<p><strong>Missão:</strong> no contador com histórico, exiba cada valor salvo como &lt;li&gt; — clique adicionar várias vezes e veja a lista crescer.</p>`,
    ferramentas: "<code>ul</code> + <code>historico.map((n,i) => &lt;li key={i}&gt;...)</code>",
    passos: ["Adicione &lt;ul&gt; com map no historico", "key={i} em cada li", "Teste clicando adicionar", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  const [historico, setHistorico] = React.useState([]);\n  function adicionar() {\n    setContador((prev) => {\n      const novo = prev + 1;\n      setHistorico((h) => [...h, novo]);\n      return novo;\n    });\n  }\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={adicionar}>adicionar</button>\n    </div>\n  );\n}`,
    dica: "ul + historico.map((n,i)=><li key={i}>{n}</li>)",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  const [historico, setHistorico] = React.useState([]);\n  function adicionar() {\n    setContador((prev) => {\n      const novo = prev + 1;\n      setHistorico((h) => [...h, novo]);\n      return novo;\n    });\n  }\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={adicionar}>adicionar</button>\n      <ul>{historico.map((n, i) => <li key={i}>{n}</li>)}</ul>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /\.map/.test(c) && /key=\{/.test(c), msg: "map + key" }, { ok: /setHistorico/.test(c), msg: "setHistorico" }]; },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "useState", revisaoDe: 3,
    refs: ["useState", "setContador"],
    titulo: "Revisão — você lembra do useState?",
    aprender: `<p><strong>Revisão</strong> da pergunta 3. Se errar, abra o Fórum → useState.</p>`,
    quiz: [
      { pergunta: "Depois de setContador(5), na próxima renderização contador será:", opcoes: ["5", "o valor antigo na mesma linha de código", "undefined"], correta: 0, explicacao: "set agenda atualização." },
      { pergunta: "Posso fazer contador++ direto no código?", opcoes: ["não — use setContador", "sim, sempre", "só no CSS"], correta: 0, explicacao: "React não detecta mutação direta." },
    ],
    passos: ["Revisão teórica", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "médio", nivelClass: "amarelo", topico: "useState", revisaoDe: 8,
    refs: ["useState", "onClick", "setContador", "math-max"],
    titulo: "Revisão — contador com 3 botões",
    missao: `<p><strong>Missão:</strong> monte um contador com três ações — igual seu <code>contador.html</code>:</p>
      <ul style="margin:8px 0 8px 18px"><li><strong>adicionar</strong> (+1)</li><li><strong>resetar</strong> (volta a 0)</li><li><strong>remover</strong> (-1, mínimo 0)</li></ul>`,
    ferramentas: "useState, onClick, setContador, Math.max(0, ...)",
    passos: ["Três botões com onClick", "remover usa Math.max(0, ...)", "Teste os três", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n    </div>\n  );\n}`,
    dica: "Junte o que fez nas perguntas 8, 10 e 12.",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador((c) => c + 1)}>adicionar</button>\n      <button onClick={() => setContador(0)}>resetar</button>\n      <button onClick={() => setContador((c) => Math.max(0, c - 1))}>remover</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /adicionar/i.test(c) && /resetar/i.test(c) && /remover/i.test(c), msg: "3 botões" }, { ok: /Math\.max/.test(c), msg: "Math.max no remover" }]; },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "boolean",
    refs: ["boolean-state", "ternario"],
    titulo: "Esconder e mostrar com boolean",
    aprender: `<p><code>useState(true)</code> + <code>{mostrar && &lt;ul&gt;...}</code> — se true mostra, se false esconde.</p>
      <p><code>setMostrar(m => !m)</code> inverte no clique.</p>`,
    quiz: [
      { pergunta: "{mostrar && <ul>} renderiza a lista quando:", opcoes: ["mostrar é true", "mostrar é false", "sempre"], correta: 0, explicacao: "&& = condicional no JSX." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "médio", nivelClass: "amarelo", topico: "boolean",
    refs: ["boolean-state"],
    titulo: "Botão para esconder/mostrar lista",
    missao: `<p><strong>Missão:</strong> adicione um botão que <strong>esconde ou mostra</strong> a lista de histórico — começa visível.</p>`,
    ferramentas: "<code>useState(true)</code>, <code>{mostrar && &lt;ul&gt;...}</code>, <code>setMostrar(m => !m)</code>",
    passos: ["State mostrar começando true", "Botão toggle", "Lista dentro de {mostrar && ...}", "Verificar"],
    codigo: `function Contador() {\n  const [historico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      <ul>{historico.map((n, i) => <li key={i}>{n}</li>)}</ul>\n    </div>\n  );\n}`,
    dica: "const [mostrar, setMostrar] = React.useState(true);",
    solucao: `function Contador() {\n  const [historico] = React.useState([1, 2, 3]);\n  const [mostrar, setMostrar] = React.useState(true);\n  return (\n    <div>\n      <button onClick={() => setMostrar((m) => !m)}>toggle</button>\n      {mostrar && <ul>{historico.map((n, i) => <li key={i}>{n}</li>)}</ul>}\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /useState\s*\(\s*true/.test(c), msg: "useState(true/false)" }, { ok: /mostrar\s*&&/.test(c), msg: "{mostrar && ...}" }]; },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "jsx",
    refs: ["ternario"],
    titulo: "Par ou ímpar com ternário",
    aprender: `<p><code>{contador % 2 === 0 ? "par" : "ímpar"}</code> — escolhe texto conforme a condição.</p>`,
    quiz: [
      { pergunta: "condição ? A : B significa:", opcoes: ["se condição verdadeira mostra A, senão B", "sempre A", "loop infinito"], correta: 0, explicacao: "If inline no JSX." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "médio", nivelClass: "amarelo", topico: "jsx",
    refs: ["ternario", "jsx-chaves"],
    titulo: "Mostrar se é par ou ímpar",
    missao: `<p><strong>Missão:</strong> abaixo do contador, mostre se o número atual é <em>par</em> ou <em>ímpar</em> (atualiza ao clicar +).</p>`,
    ferramentas: "ternário com <code>contador % 2 === 0</code>",
    passos: ["Linha com ternário par/ímpar", "Botão + já existe", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador((c) => c + 1)}>+</button>\n    </div>\n  );\n}`,
    dica: "<p>{contador % 2 === 0 ? 'par' : 'ímpar'}</p>",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <p>{contador % 2 === 0 ? "par" : "ímpar"}</p>\n      <button onClick={() => setContador((c) => c + 1)}>+</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /\?/.test(c) && /:/.test(c), msg: "ternário" }, { ok: /%/.test(c), msg: "% 2" }]; },
  },
  {
    tipo: "teoria", nivel: "médio", nivelClass: "amarelo", topico: "useState",
    refs: ["useState"],
    titulo: "Dois states: contador e passo",
    aprender: `<p>Você pode ter vários <code>useState</code> no mesmo componente. Ex: <code>passo</code> controla quanto soma por clique.</p>`,
    quiz: [
      { pergunta: "Dois useStates no mesmo componente:", opcoes: ["é normal e comum", "é proibido", "só funciona no App"], correta: 0, explicacao: "Cada um guarda uma coisa diferente." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "médio", nivelClass: "amarelo", topico: "useState",
    titulo: "Contador com passo configurável",
    missao: `<p><strong>Missão:</strong> o botão <em>adicionar</em> soma um valor chamado <code>passo</code> (começa em 1). Tenha também botão <em>passo +</em> que aumenta o passo.</p>`,
    ferramentas: "2 useStates: contador e passo, <code>setContador(c => c + passo)</code>",
    passos: ["useState(1) para passo", "Mostre passo na tela", "adicionar soma +passo", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n    </div>\n  );\n}`,
    dica: "const [passo, setPasso] = React.useState(1);",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  const [passo, setPasso] = React.useState(1);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <p>Passo: {passo}</p>\n      <button onClick={() => setPasso((p) => p + 1)}>passo +</button>\n      <button onClick={() => setContador((c) => c + passo)}>adicionar</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: (c.match(/useState/g) || []).length >= 2, msg: "2+ useStates" }, { ok: /\+\s*passo/.test(c), msg: "somar + passo" }]; },
  },
  {
    tipo: "teoria", nivel: "avançado", nivelClass: "vermelho", topico: "spread",
    refs: ["spread-obj"],
    titulo: "State como objeto",
    aprender: `<p>Um objeto no state: <code>useState({ contador: 0, passo: 1 })</code>. Atualize com spread: <code>{...p, contador: p.contador + 1}</code>.</p>`,
    quiz: [
      { pergunta: "Ao mudar objeto no state:", opcoes: ["crie objeto novo com spread", "mude p.contador++ direto", "use push"], correta: 0, explicacao: "Mesma regra do array." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "avançado", nivelClass: "vermelho", topico: "spread",
    refs: ["spread-obj"],
    titulo: "Contador e passo num só objeto",
    missao: `<p><strong>Missão:</strong> em vez de dois useStates, guarde <code>{ contador: 0, passo: 1 }</code> num único state <code>config</code>. Botão + soma 1 no contador usando spread.</p>`,
    ferramentas: "<code>useState({...})</code> e <code>setConfig(p => ({...p, contador: p.contador + 1}))</code>",
    passos: ["useState com objeto", "Leia config.contador no JSX", "Botão + atualiza com spread", "Verificar"],
    codigo: `function Contador() {\n  return <div>...</div>;\n}`,
    dica: "const [config, setConfig] = React.useState({ contador: 0, passo: 1 });",
    solucao: `function Contador() {\n  const [config, setConfig] = React.useState({ contador: 0, passo: 1 });\n  return (\n    <div>\n      <p>{config.contador}</p>\n      <button onClick={() => setConfig((p) => ({ ...p, contador: p.contador + 1 }))}>+</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /useState\s*\(\s*\{/.test(c), msg: "useState({})" }, { ok: /\.\.\.(?:prev|p)/.test(c), msg: "spread ao atualizar" }]; },
  },
  {
    tipo: "teoria", nivel: "avançado", nivelClass: "vermelho", topico: "strings",
    refs: ["calculadora"],
    titulo: "Template strings (sua calculadora)",
    aprender: `<p>Na calculadora você usa <code>\`\${operacao}\${input}\`</code> para montar texto. Mesma ideia pro histórico de operações.</p>`,
    quiz: [
      { pergunta: "Template string usa:", opcoes: ["crase ` e ${variavel}", "só aspas '", "colchetes []"], correta: 0, explicacao: "Interpola variáveis no texto." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "avançado", nivelClass: "vermelho", topico: "strings",
    refs: ["spread-array"],
    titulo: "Histórico de textos (+1, +2...)",
    missao: `<p><strong>Missão:</strong> cada clique salva no histórico uma <strong>string</strong> tipo <code>+1</code>, <code>+2</code>... e mostra a lista na tela.</p>`,
    ferramentas: "template string <code>`+${n}`</code> + spread no historico + map",
    passos: ["Ao adicionar, salve string no historico", "Mostre com map", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  const [historico, setHistorico] = React.useState([]);\n  return <div>...</div>;\n}`,
    dica: "setHistorico(h => [...h, `+${n}`])",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  const [historico, setHistorico] = React.useState([]);\n  function add() {\n    setContador((c) => {\n      const n = c + 1;\n      setHistorico((h) => [...h, \`+\${n}\`]);\n      return n;\n    });\n  }\n  return (\n    <div>\n      <p>{contador}</p>\n      <button onClick={add}>+</button>\n      <ul>{historico.map((s, i) => <li key={i}>{s}</li>)}</ul>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /`/.test(c), msg: "template string" }, { ok: /\[\.\.\./.test(c), msg: "spread" }]; },
  },
  {
    tipo: "teoria", nivel: "avançado", nivelClass: "vermelho", topico: "arrays",
    refs: ["filter"],
    titulo: "Limpar uma lista",
    aprender: `<p><code>setHistorico([])</code> zera a lista. <code>filter</code> remove itens específicos mantendo os outros.</p>`,
    quiz: [
      { pergunta: "setHistorico([]) faz:", opcoes: ["lista vazia nova", "apaga o componente", "só esconde visualmente"], correta: 0, explicacao: "Reset do array no state." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "avançado", nivelClass: "vermelho", topico: "arrays",
    refs: ["filter"],
    titulo: "Botão limpar histórico",
    missao: `<p><strong>Missão:</strong> adicione botão <em>limpar</em> que apaga todos os itens do histórico (volta pra lista vazia).</p>`,
    ferramentas: "<code>setHistorico([])</code>",
    passos: ["Botão limpar", "onClick zera o array", "Verificar"],
    codigo: `function Contador() {\n  const [historico, setHistorico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      <ul>{historico.map((n,i)=><li key={i}>{n}</li>)}</ul>\n    </div>\n  );\n}`,
    dica: "onClick={() => setHistorico([])}",
    solucao: `function Contador() {\n  const [historico, setHistorico] = React.useState([1, 2, 3]);\n  return (\n    <div>\n      <button onClick={() => setHistorico([])}>limpar</button>\n      <ul>{historico.map((n, i) => <li key={i}>{n}</li>)}</ul>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /setHistorico\s*\(\s*\[\s*\]\s*\)/.test(c), msg: "setHistorico([])" }]; },
  },
  {
    tipo: "teoria", nivel: "avançado", nivelClass: "vermelho", topico: "props",
    refs: ["props", "desestruturacao"],
    titulo: "Props — configuração de fora",
    aprender: `<p>O componente pai passa dados: <code>&lt;Contador passo={3} /&gt;</code>. O filho recebe com <code>{ passo = 1 }</code>.</p>
      <p>Props = leitura. State = memória interna.</p>`,
    quiz: [
      { pergunta: "passo = 1 na função significa:", opcoes: ["valor padrão se o pai não passar", "passo sempre 1", "erro de sintaxe"], correta: 0, explicacao: "Default na desestruturação." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "avançado", nivelClass: "vermelho", topico: "props",
    refs: ["props", "componente"],
    titulo: "Passo definido pelo componente pai",
    missao: `<p><strong>Missão:</strong> o <code>App</code> passa <code>passo={3}</code> pro <code>Contador</code>. O botão + deve somar +3 cada clique.</p>`,
    ferramentas: "<code>function Contador({ passo = 1 })</code> e <code>&lt;Contador passo={3} /&gt;</code>",
    passos: ["Contador recebe { passo }", "Somar + passo no clique", "App renderiza <Contador passo={3} />", "Verificar"],
    codigo: `function Contador(/* TODO */) {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>{contador}</p>\n      <button onClick={() => setContador((c) => c + 1)}>+</button>\n    </div>\n  );\n}\nfunction App() {\n  return <Contador />;\n}`,
    dica: "function Contador({ passo = 1 }) e somar + passo",
    solucao: `function Contador({ passo = 1 }) {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>{contador}</p>\n      <button onClick={() => setContador((c) => c + passo)}>+</button>\n    </div>\n  );\n}\nfunction App() {\n  return <Contador passo={3} />;\n}`,
    validar(c) { return [{ ok: /\{\s*passo/.test(c), msg: "desestruturar passo" }, { ok: /<Contador\s+passo=/.test(c), msg: "<Contador passo={...}/>" }]; },
  },
  {
    tipo: "teoria", nivel: "avançado", nivelClass: "vermelho", topico: "eventos", revisaoDe: 7,
    refs: ["onClick", "eventos"],
    titulo: "Revisão — onClick certo e errado",
    aprender: `<p><strong>Revisão</strong> da pergunta 7: onClick precisa de função, não de chamada imediata.</p>`,
    quiz: [
      { pergunta: "Qual opção quebra ao renderizar?", opcoes: ["onClick={() => add()}", "onClick={add()}", "onClick={add}"], correta: 1, explicacao: "add() executa na hora, não no clique." },
      { pergunta: "onClick={add} funciona quando add é:", opcoes: ["uma função que você definiu", "um número", "uma string"], correta: 0, explicacao: "Referência de função é válida." },
    ],
    passos: ["Revisão", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "avançado", nivelClass: "vermelho", topico: "useState",
    titulo: "Contador de quantos cliques",
    missao: `<p><strong>Missão:</strong> além do contador, mostre <em>quantas vezes</em> o usuário clicou em adicionar (state <code>cliques</code> separado).</p>`,
    ferramentas: "2 useStates + 2 sets no mesmo handler",
    passos: ["State cliques começando 0", "A cada adicionar: +1 contador e +1 cliques", "Mostre ambos na tela", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return <div>...</div>;\n}`,
    dica: "function add() { setContador(...); setCliques(...); }",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  const [cliques, setCliques] = React.useState(0);\n  function add() {\n    setContador((c) => c + 1);\n    setCliques((k) => k + 1);\n  }\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <p>Cliques: {cliques}</p>\n      <button onClick={add}>adicionar</button>\n    </div>\n  );\n}`,
    validar(c) { return [{ ok: /cliques/i.test(c), msg: "state cliques" }, { ok: /setCliques/.test(c), msg: "setCliques" }]; },
  },
  {
    tipo: "teoria", nivel: "avançado", nivelClass: "vermelho", topico: "react",
    refs: ["componente", "createRoot"],
    titulo: "Estrutura App + createRoot",
    aprender: `<p>Arquivo real: <code>Contador</code> (lógica) → <code>App</code> (monta a página) → <code>createRoot().render(&lt;App /&gt;)</code> (liga ao HTML).</p>`,
    quiz: [
      { pergunta: "&lt;Contador /&gt; no JSX significa:", opcoes: ["usar o componente Contador aqui", "criar tag HTML contador", "importar CSS"], correta: 0, explicacao: "Componente como elemento." },
    ],
    passos: ["Leia e responda", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "avançado", nivelClass: "vermelho", topico: "react",
    refs: ["componente"],
    titulo: "Criar o App com &lt;main&gt;",
    missao: `<p><strong>Missão:</strong> crie <code>function App()</code> que envolve o <code>Contador</code> numa tag <code>&lt;main&gt;</code> — igual seu <code>contador.html</code>.</p>`,
    ferramentas: "function App + &lt;main&gt;&lt;Contador /&gt;&lt;/main&gt;",
    passos: ["Adicione function App abaixo do Contador", "return com main e Contador dentro", "Verificar"],
    codigo: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador((p) => p + 1)}>+</button>\n    </div>\n  );\n}\n// TODO App`,
    dica: "function App() { return <main><Contador /></main>; }",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <button onClick={() => setContador((p) => p + 1)}>+</button>\n    </div>\n  );\n}\nfunction App() {\n  return (\n    <main>\n      <Contador />\n    </main>\n  );\n}`,
    validar(c) { return [{ ok: /function App/.test(c), msg: "function App" }, { ok: /<Contador/.test(c) && /<main>/.test(c), msg: "main > Contador" }]; },
  },
  {
    tipo: "teoria", nivel: "avançado", nivelClass: "vermelho", topico: "calculadora",
    refs: ["calculadora", "map", "children"],
    titulo: "Sua calculadora (modelo.html)",
    aprender: `<p>Grade de botões com <strong>map duplo</strong>: <code>buttons.map(row => row.map(btn => ...))</code>.</p>
      <p>Componentes <code>Button</code>, <code>Card</code>, <code>Text</code> usam <code>children</code> — conteúdo entre as tags.</p>`,
    quiz: [
      { pergunta: "map duplo na calculadora serve para:", opcoes: ["renderizar linhas e colunas de botões", "somar números", "apagar state"], correta: 0, explicacao: "Matriz de botões." },
      { pergunta: "operacao e result no Calculator são:", opcoes: ["dois useStates (strings)", "props do pai", "só CSS"], correta: 0, explicacao: "State da lógica da calc." },
    ],
    passos: ["Leia Fórum → Calculadora", "Verificar"],
  },
  {
    tipo: "pratica", modo: "escrever", nivel: "avançado", nivelClass: "vermelho", topico: "projeto",
    refs: ["componente", "regras-hooks", "map", "spread-array", "boolean-state", "math-max"],
    titulo: "Projeto final — seu contador.html",
    missao: `<p><strong>Missão final:</strong> monte o contador completo com tudo que aprendeu:</p>
      <ul style="margin:8px 0 8px 18px;line-height:1.65">
        <li>contador + passo configurável</li>
        <li>adicionar, resetar, remover (Math.max)</li>
        <li>histórico com map + toggle mostrar/esconder</li>
        <li>App com &lt;main&gt;</li>
      </ul>
      <p>Quando passar, copie pro seu <code>contador.html</code> real!</p>`,
    ferramentas: "useState, onClick, spread, map, key, boolean &&, Math.max, App",
    porque: "Isso é o que um dev front júnior monta: state + eventos + listas + composição.",
    passos: ["Monte Contador completo", "function App com main", "Teste tudo na preview", "Verificar — depois copie pro contador.html"],
    codigo: `function Contador() {\n  // SEU CONTADOR FINAL\n}\nfunction App() {\n  return (\n    <main>\n      {/* Contador aqui */}\n    </main>\n  );\n}`,
    dica: "Use a solução como guia e adapte ao seu estilo.",
    solucao: `function Contador() {\n  const [contador, setContador] = React.useState(0);\n  const [passo, setPasso] = React.useState(1);\n  const [historico, setHistorico] = React.useState([]);\n  const [mostrar, setMostrar] = React.useState(true);\n  function adicionar() {\n    setContador((c) => {\n      const novo = c + passo;\n      setHistorico((h) => [...h, novo]);\n      return novo;\n    });\n  }\n  return (\n    <div>\n      <p>Contador: {contador}</p>\n      <p>Passo: {passo}</p>\n      <button onClick={adicionar}>adicionar</button>\n      <button onClick={() => setContador(0)}>resetar</button>\n      <button onClick={() => setContador((c) => Math.max(0, c - passo))}>remover</button>\n      <button onClick={() => setPasso((p) => p + 1)}>passo +</button>\n      <button onClick={() => setPasso((p) => Math.max(1, p - 1))}>passo -</button>\n      <button onClick={() => setMostrar((m) => !m)}>histórico</button>\n      {mostrar && (\n        <ul>{historico.map((n, i) => <li key={i}>Clique → {n}</li>)}</ul>\n      )}\n    </div>\n  );\n}\nfunction App() {\n  return (\n    <main>\n      <Contador />\n    </main>\n  );\n}`,
    validar(c) {
      return [
        { ok: /function Contador/.test(c) && /function App/.test(c), msg: "Contador + App" },
        { ok: /<main>/.test(c) && /<Contador/.test(c), msg: "main > Contador" },
        { ok: /\.map/.test(c) && /setHistorico/.test(c) && /setPasso/.test(c), msg: "histórico + passo" },
        { ok: /Math\.max/.test(c), msg: "Math.max" },
      ];
    },
  },
];
